### PR TITLE
Fixes #12112 - Added a function that enables removing credentials on need

### PR DESCRIPTION
**Pull request by alongoldboim**

### CODE REVIEW

**Comment by alongoldboim** [comment]
@mbacovsky ready to be pushed.

**Comment by mbacovsky** [comment]
Looks good, Could you add some test?

**Comment by alongoldboim** [comment]
@mbacovsky Test added.

**Comment by alongoldboim** [comment]
[test]

**Comment by mbacovsky** [comment]
Thanks for the patch. I appreciate the test added, @alongoldboim 
:+1:

**Pull request merged**
