### PR TITLE
Fixes #66 - update cache on error responses

### LINKED ISSUE #66: API cache not auto reloaded after an API call with an error response
Refreshing the cache is skipped when a http call raises an exception:
https://github.com/Apipie/apipie-bindings/blob/master/lib/apipie_bindings/api.rb#L238-L247

It should be checking the cache even on error responses.

### PR DESCRIPTION
**Pull request by tstrachota**

### CODE REVIEW

**Comment by tstrachota** [comment]
Tests fail due to some bundle install failures on some ruby versions. Not sure why.

**Comment by mbacovsky** [comment]
@tstrachota please rebase to fix the tests

**Comment by tstrachota** [comment]
@mbacovsky rebased

**Comment by mbacovsky** [comment]
:+1: LGTM. Thanks @tstrachota!

**Pull request merged**
